name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup pnpm and install
        uses: pnpm/action-setup@v4

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: Build workspace
        run: /
          cd packages/core
          npx -y tsc -b tsconfig.json --clean
          npx -y tsc -b tsconfig.json
          cd ../../
          for d in packages/*; do
            if [ -f "$d/package.json" ]; then
              name=$(jq -r .name "$d/package.json")
              case "$name" in
                @db2lake/driver-*)
                  echo "Publishing $name from $d"
                  cd "$d"
                  npx -y tsc -b tsconfig.json --clean
                  npx -y tsc -b tsconfig.json
                  cd -
                  ;;
              esac
            fi
          done

      - name: Run tests
        run: npx vitest run

      - name: Diagnostic - list core src (for debugging)
        if: failure()
        run: ls -la packages/core || true
