name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Diagnostic - show environment and core files
        run: |
          echo "PWD: $(pwd)"
          node -v
          npm -v
          npx -v || true
          tsc -v || true
          echo '--- packages/core ---'
          ls -la packages/core || true
          echo '--- packages/core/src ---'
          ls -la packages/core/src || true
          echo '--- packages/core/tsconfig.json ---'
          cat packages/core/tsconfig.json || true

      - name: Build core package first (root tsc invocation)
        run: npx tsc -p packages/core/tsconfig.json

      - name: Build remaining packages
        run: npm --workspaces run build

      - name: Run tests
        run: npx vitest run

      - name: Diagnostic - list core src (for debugging)
        if: failure()
        run: ls -la packages/core || true
