name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: Build workspace
        run: pnpm run build

      - name: Run tests
        run: npx vitest run

      - name: Diagnostic - list core src (for debugging)
        if: failure()
        run: ls -la packages/core || true
