name: Publish @db2lake/core

on:
  push:
    branches: [ master ]
    paths:
      - 'packages/core/**'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Build and publish core
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: List src files
        run: ls -l packages/core/src

      - name: Check parent tsconfig
        run: ls -l ../../tsconfig.json
        working-directory: packages/core

      - name: Setup pnpm and install
        uses: pnpm/action-setup@v4

      - name: Install workspace dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Clean workspace and Build (ordered)
        run: |
          # Clean any previous build outputs across the workspace
          pnpm -w -s -r run clean || true
          # Run a fresh composite build
          pnpm run build:ordered

      - name: Publish core to npm
        run: |
          cd packages/core
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}